### ISSUE TITLE
Error: yt-dlp is not installed

### ISSUE THREAD

**Issue by wiemar7** [anga83/tiktok-downloader#2]
i have error when i run this script:

Welcome to the TikTok Downloader.
Error: yt-dlp is not installed.
Please install yt-dlp before using this script.

i put yt-dlp.exe and ffmpeg.exe and script on one folder and add to PATH

my mistake. not yt-dlp.exe. i must use yt-dlp. but now i have error:

 ffmpeg is not installed.
 Please install ffmpeg to use this feature.

problem solved. i just install ffmpeg using ubuntu from ms store.
but now when im put tiktok url i got errors on line: 788 and 796

**Comment by anga83** [comment]
Hi there!
How do you run the script on a WIndows system (Cygwin, WSL, ...)?

I've just released version 2.3, which should be capable of using Windows .exe binaries, but WSL probably likes the linux binaries better.

Errors in line 788 and 796 are probably related to missing `jq` .  Can you confirm if `jq` is installed?

Can you please update to the latest version of the script and then post the "Debug information" you get when you run "Help"?

**Comment by wiemar7** [comment]
im sitting all day to run this script for live mode. im little newbie about programing. i just turn on developer mode on windows, turn on windows function: Subsystem for Linux (WSL). use cygwin for chmod +x. installed ffmpeg using ubuntu from microsoft store and yt-dlp to path. then in powershell i type: bash tiktok-downloader.sh.
what is that "jq"?
from help option i have this:
`Debug information (include in issues):
  Script version: 2.2
  Bash version 5.1.16(1)-release.
  yt-dlp version: 2022.10.04
  ffmpeg version: 4.4.2-0ubuntu0.22.04.1
  ffprobe version: 4.4.2-0ubuntu0.22.04.1
  Linux distribution: Ubuntu 22.04.1 LTS @ Linux 4.4.0-19041-Microsoft x86_64`

**Comment by anga83** [comment]
1. open WSL and run this command: `sudo apt update && sudo apt --assume-yes install jq curl rev sed grep`
3. download [latest version](https://github.com/anga83/tiktok-downloader/archive/refs/heads/main.zip)
4. try again

**Comment by wiemar7** [comment]
Room ID: 7159966707677743878
Retrieving live infos.../mnt/c/ytdl/tiktok-downloader.sh: line 873: jq: command not found
Error: Live stream not found.

**Comment by anga83** [comment]
Looks like `jq` still isn't installed. What does `jq --version` print?

Regarding `rev`:  try `sudo apt --assume-yes install util-linux`

Lastly, I'd like you to [update](https://github.com/anga83/tiktok-downloader/archive/refs/heads/main.zip) the script again.

Unfortunately, I don't have a WSL installation here, so I can't reproduce your issue.

**Comment by wiemar7** [comment]
You're right. i don't have "jq" installed (use: sudo apt install jq) and "rev" from second line from your post. now it is working.
do you have maybe discord? i have question about something else
