### ISSUE TITLE
Avatar downloads are named as avatar.jpg.jpg

### ISSUE THREAD

**Issue by luckman212** [anga83/tiktok-downloader#3]
Nice little script!

When downloading the avatar, the filename extension is duplicated, because the `$output_name` variable already contains the extension.

https://github.com/anga83/tiktok-downloader/blob/2847b843ab806c1a18819dea9ddbc4cd5796871d/tiktok-downloader.sh#L760

**Comment by anga83** [comment]
Hi!
Thank you :)

Will be fixed in the next release.

Kind regards!
